import Abacaxi from './abacaxi.jpg'
import Açúcar from './acucar.jpg'
import Água from './agua.jpg'
import Almoço from './Almoco.jpg'
import Amor from './amor.jpg'
import Apostila from './Apostila.png'
import Bala from './bala.jpg'
import Bola from './ball.jpg'
import Beijo from './beijo.jpg'
import Blusa from './blusa.png'
import Cachorro from './cachorro.jpg'
import Caderno from './caderno.png'
import Casa from './casa.png'
import Cidade from './cidade.jpg'
import Colher from './colher.jpg'
import Coração from './coração.jpg'
import Costas from './costas.jpg'
import Dinheiro from './dinheiro.jpg'
import Diogo from './diogo.jpg'
import Diego from './diego.png'
import Donzela from './donzela.jpg'
import Faca from './faca.jpg'
import Foca from './foca.jpg'
import Fruta from './fruta.jpg'
import Gato from './gato.jpg'
import Geladeira from './geladeira.png'
import Gelatina from './gelatina.jpg'
import Gelo from './Gelo.jpg'
import Gilvan from './gilvan.png'
import Girassol from './girassol.jpg'
import Grama from './grama.jpg'
import Jaqueta from './jaqueta.jpg'
import Jovem from './jovem.jpg'
import Laranja from './laranja.jpg'
import Leão from './leao.jpg'
import Lençol from './lencol.jpg'
import Limpar from './limpar.jpg'
import Loira from './loira.jpg'
import Lua from './lua.jpg'
import Macaco from './macaco.jpg'
import Medico from './medico.jpeg'
import Medir from './medir.jpg'
import Melancia from './melancia.jpg'
import Menina from './menina.jpg'
import Mia from './mia.jpg'
import Milho from './milho.jpg'
import Mingau from './mingau.jpg'
import Minhoca from './minhoca.jpg'
import Olho from './olho.jpg'
import Parceiro from './parceiro.jpg'
import Poliana from './poliana.png'
import Peixe from './peixe.jpg'
import Pilar from './pilar.jpg'
import Refrigerante from './refrigerante.jpg'
import Roupa from './roupa.jpg'
import Sol from './sol.jpg'
import Tania from './tania.png'
import Telefone from './telefone.jpg'
import Travessura from './travessura.jpg'
import Tucano from './tucano.jpg'
import Uva from './uva.jpg'
import Verde from './verde.jpg'
import Vermelho from './vermelho.jpg'
import Zen from './zen.jpg'


export const Objetos = {
  Abacaxi,Açúcar,Água,Almoço,Amor,Apostila,Bala,Bola,Beijo,Blusa,Cachorro,Caderno,
Casa,Cidade,Colher,Coração,Costas,Dinheiro,Diogo,Diego,Donzela,Faca,Foca,Fruta,
Gato,Geladeira,Gelatina,Gelo,Gilvan,Girassol,Grama,Jaqueta,Jovem,
Laranja,Leão,Lençol,Limpar,Loira,Lua,Macaco,Medico,Medir,Melancia,
Menina,Mia,Milho,Mingau,Minhoca,Olho,Parceiro,Poliana,Peixe,Pilar,Refrigerante,
Roupa,Sol,Tania,Telefone,Travessura,Tucano,Uva,Verde,Vermelho,
Zen
}


